// <auto-generated />
using System;
using Assigment3_1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assigment31.Migrations
{
    [DbContext(typeof(SportsProContext))]
    partial class SportsProContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assigment3_1.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("decimal(11,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ProductCode = "DRAFT10",
                            ProductName = "Draft Manager 1.0",
                            ReleaseDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductID = 2,
                            ProductCode = "DRAFT20",
                            ProductName = "Draft Manager 2.0",
                            ReleaseDate = new DateTime(2019, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearlyPrice = 5.99m
                        },
                        new
                        {
                            ProductID = 3,
                            ProductCode = "LEAG10",
                            ProductName = "League Scheduler 1.0",
                            ReleaseDate = new DateTime(2016, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductID = 4,
                            ProductCode = "LEAGD10",
                            ProductName = "League Scheduler Deluxe 1.0",
                            ReleaseDate = new DateTime(2016, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearlyPrice = 7.99m
                        },
                        new
                        {
                            ProductID = 5,
                            ProductCode = "TEAM10",
                            ProductName = "Team Manager 1.0",
                            ReleaseDate = new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductID = 6,
                            ProductCode = "TRNY10",
                            ProductName = "Tournament Master 1.0",
                            ReleaseDate = new DateTime(2015, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearlyPrice = 4.99m
                        },
                        new
                        {
                            ProductID = 7,
                            ProductCode = "TRNY20",
                            ProductName = "Tournament Master 2.0",
                            ReleaseDate = new DateTime(2018, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearlyPrice = 5.99m
                        });
                });

            modelBuilder.Entity("Assigment3_1.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TechnicianID");

                    b.ToTable("technicians");

                    b.HasData(
                        new
                        {
                            TechnicianID = 11,
                            Email = "alison@sportsprosoftware.com",
                            Name = "Alison Diaz",
                            Phone = "800-555-0443",
                            ReleaseDate = new DateTime(2023, 2, 7, 4, 59, 58, 475, DateTimeKind.Local).AddTicks(6040)
                        },
                        new
                        {
                            TechnicianID = 12,
                            Email = "jason@sportsprosoftware.com",
                            Name = "Jason Lee",
                            Phone = "800-555-0444",
                            ReleaseDate = new DateTime(2023, 2, 7, 4, 59, 58, 475, DateTimeKind.Local).AddTicks(6044)
                        },
                        new
                        {
                            TechnicianID = 13,
                            Email = "awilson@sportsprosoftware.com",
                            Name = "Andrew Wilson",
                            Phone = "800-555-0449",
                            ReleaseDate = new DateTime(2023, 2, 7, 4, 59, 58, 475, DateTimeKind.Local).AddTicks(6045)
                        },
                        new
                        {
                            TechnicianID = 14,
                            Email = "gunter@sportsprosoftware.com",
                            Name = "Gunter Wendt",
                            Phone = "800-555-0400",
                            ReleaseDate = new DateTime(2023, 2, 7, 4, 59, 58, 475, DateTimeKind.Local).AddTicks(6046)
                        },
                        new
                        {
                            TechnicianID = 15,
                            Email = "gfiori@sportsprosoftware.com",
                            Name = "Gina Fiori",
                            Phone = "800-555-0459",
                            ReleaseDate = new DateTime(2023, 2, 7, 4, 59, 58, 475, DateTimeKind.Local).AddTicks(6048)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
